### ISSUE TITLE
Missing a file. Unable to compile.

### ISSUE THREAD

**Issue by hdclark** [charlyisidore/GeomLibC--#1]
[hal@Crushernator charlyisidore-GeomLibC---dc68926]$ g++ main.cpp
In file included from Parametric.hpp:30:0,
                 from Spline.hpp:30,
                 from NURBS.hpp:30,
                 from main.cpp:1:
Vector.hpp:412:20: fatal error: osg/Vec2: No such file or directory
compilation terminated.

Where can I find osg/Vec2? Can I safely remove it from Vector.hpp ?

**Comment by charlyisidore** [comment]
osg/Vec2 is a part of OpenSceneGraph (a 3D library).

You don't need Vec2 to compile but you should remove code between line 410 and line 433 (These are Vector to Vec2/Vec3 converters).

I think I should put code to detect OpenSceneGraph with preprocessor constants (like #if OSG ... #endif).
